### ISSUE TITLE
fallback option is broken, second call to fallback crashes the SNIProxy with sniproxy SIGABRT, first call goes fine.

### ISSUE THREAD

**Issue by balyanrobin** [dlundquist/sniproxy#160] opened 2015-04-02 07:34 UTC
Hi,

Thanks for providing a great software to the community. I just downloaded the latest Sniproxy code and installed it. I noticed when the request goes to fallback domain it crashes in the second call. First call goes fine. Do you have any Idea?

Thanks i advance for your efforts and time.

Robin

**Comment by balyanrobin** [comment] 2015-04-02 08:00
When request does not include sin-extension/hostname, i see below errors in error.log first time and second time for the same call SniProxy crashes - 

2015-04-02 07:53:05 Request from [::ffff:xx.xxx.xx.xx]:53536 did not include a hostname
2015-04-02 07:53:05 Invalid hostname (null) in client request


My configuration is below, 
listen 443 {
	protocol tls
	table https_hosts
	fallback localhost:8080
	access_log {
		# Same options as error_log
		filename /logs/sni_https.log
		priority debug
	}
}

**Comment by dlundquist** [comment] 2015-04-02 14:45
Could you try it with `fallback 127.0.0.1:8080` instead of `fallback localhost:8080`?

**Comment by dlundquist** [comment] 2015-04-04 18:43
I've added a test in 93af73a3c and have been been able to reproduce this behavior.

**Comment by balyanrobin** [comment] 2015-04-05 05:02
Ok great, Do you still want me to test 127.0.0.1 or you got the handle on the issue?

**Comment by dlundquist** [comment] 2015-04-08 04:33
@balyanrobin I can't reproduce your crash. Using an IP literal rather than a hostname will allow the fallback server to to be used even if there is a problem resolving DNS queries. I've added a warning in the 0.4.0 release to discourage this configuration, although I could see certain applications where this could be useful so its only a warning. In the case of localhost, using ::1 or 127.0.0.1 is a good idea.

**Closed by dlundquist** 2015-04-08 04:33 UTC

**Comment by balyanrobin** [comment] 2015-04-08 08:14
for me it is crashing even if i use IP literal also like : fallback 127.0.0.1:8080

**Comment by balyanrobin** [comment] 2015-04-08 08:52
below line in connection.c under resolve_server_address is destroying the fallback memory, and hurting the next connection falling back on the same fallback server. Could you please review it once

free(server_address);
