### ISSUE TITLE
reloading tables only

### ISSUE THREAD

**Issue by vavrecan** [dlundquist/sniproxy#199] opened 2016-03-20 19:55 UTC
do you think it would be possible to add SIGUSR2 or some other signal just to reload tables? 
it seems like the reloading log files is causing crashes (I compiled sniproxy for openwrt and I am not able to get the dump out) and just having tables reloaded would do the trick

**Comment by dlundquist** [comment] 2016-03-22 18:52
You could add an `only_tables` flag to `reload_config()`, add another case to `signal_cb()` and register an additional signal watcher for SIGUSR2 in `main()` to accomplish this. I'm curious why it is crashing when reloading the logging, that certainly is not expected behavior.

**Comment by dlundquist** [comment] 2016-06-21 21:00
Closing this issue since I've outlined how this feature could be implemented, it seems of limited use to the larger user base and there have been no updates in the last month.

**Closed by dlundquist** 2016-06-21 21:00 UTC
Labels: Feature, Needs Info
